[theme]
primaryColor = "#117B68"
backgroundColor = "#F6F8FA"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#182D3B"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
